# Generated by Django 3.1.3 on 2021-04-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesture',
            name='mapped_text',
            field=models.CharField(max_length=100),
        ),
    ]
