# Generated by Django 3.1.7 on 2021-04-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gesture',
            name='recording_duration',
        ),
    ]
