# Generated by Django 3.1.7 on 2021-04-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_remove_gesture_recording_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesture',
            name='rd',
            field=models.IntegerField(default=0),
        ),
    ]
